# Page settings
baseurl = "https://takuyakou.github.io/portfolio/"
title = "Portfolio"
languageCode = "ja-jp"
theme = "hugo-elate-theme"

[params]
  

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "Portfolio"
    home = "Home"
    work = "Works"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "PORTFOLIO"
    subtitle = 'by <a href="https://twitter.com/takuya_prog" target="_blank">Takuya kou</a>'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Blog"
    description = "学習記録や勉強記録をまとめています"
    url = "#"
    button = "Read"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Github"
    description = "これまでの開発記録まとめています"
    url = "#"
    button = "OPEN"
    icon = "icon-github"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Twitter"
    description = "DMなどはこちらからお気軽にどうぞ"
    url = "https://twitter.com/takuya_prog"
    button = "Click Me"
    icon = "icon-twitter"
    img = "img_10.jpg"

  # Work section
  [params.work]
    enable = true
    title = "Works"
    description = "開発したアプリケーションやページです。"
    footertext = '<a href="https://github.com/Takuyakou" target="_blank">Github</a>'

    [[params.work.row]]
      img = "Portfolio1.jpg"
      title = "Portfolio"
      subtitle = 'Github Pages/Hugo'
      url = "https://takuyakou.github.io/portfolio/"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Techgram"
      subtitle = "rails/techpitcopy"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "主に使っているのはHTML/CSS/Javascript/Ruby on Rails<br>最近はフロントエンド周りにも興味を持っています。"


    [[params.about.item]]
      name = "Takuya Kou"
      position = "Web Developer"
      description = '東京在住の26歳のエンジニア志望。主に学習しているのはRuby on Rails。現在転職活動中です。<a href="https://takuyakou.hatenablog.com/entry/profile" target="_blank">簡単な自己紹介はこちら</a>'
      img = "icon.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-github", "https://github.com/Takuyakou"]
      ]
 

  # Contact section
  [params.contact]
    enable = true
    title = "Contact"
    description = "現在求職中です。未経験からでも受け入れて下さる企業は気軽にお声がけ下さい。"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Tokyo"],
        ["icon-twitter", '<a href="https://twitter.com/takuya_prog" target="_blank">Twitter</a>'],
        ["icon-envelope", "takuya.engineer@gmail.com"],
        ["icon-globe", '<a href="https://takuyakou.hatenablog.com/" target="_blank">Blog</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; All Rights Reserved. by <a href="https://themes.gohugo.io/hugo-elate-theme/" target="_blank" rel="noopener">Elate theme</a> <br>for <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>'
    links = [
        ["icon-twitter", "https://twitter.com/takuya_prog"],
        ["icon-github", "https://github.com/Takuyakou"]
      ]
